import { fs, hp, spacing, wp } from '@/utils/responsive';
import { StyleSheet } from 'react-native';
import { FONTS } from './global';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  blueSection: {
    position: 'absolute',
    top: -37,
    left: 0,
    right: 0,
    height: hp(255),
    backgroundColor: '#0000FF',
  },
  backButton: {
    position: 'absolute',
    top: hp(20),
    left: spacing.md,
    width: wp(40),
    height: hp(40),
    backgroundColor: 'transparent',
    borderColor: '#FAFAFA',
    borderWidth: 1,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  welcomeText: {
    position: 'absolute',
    top: hp(90),
    left: spacing.xl,
    right: spacing.xl,
    color: '#FFFFFF',
    fontSize: fs(42),
    fontFamily: FONTS.bold,
    lineHeight: fs(50),
  },
  tabsContainer: {
    position: 'absolute',
    top: hp(220),
    left: wp(30),
    right: wp(30),
    zIndex: 5,
  },
  formContainer: {
    position: 'absolute',
    top: hp(290),
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: spacing.xl,
  },
  label: {
    fontSize: fs(16),
    fontFamily: FONTS.semibold,
    color: '#000000',
    marginBottom: hp(8),
    marginTop: hp(14),
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 12,
    paddingHorizontal: spacing.md,
    paddingVertical: hp(10),
    fontSize: fs(16),
    fontFamily: FONTS.regular,
    color: '#000000',
    minHeight: hp(48),
  },
  inputFocused: {
    borderColor: '#A3A3A3',
    borderWidth: 2.2,
  },
  passwordContainer: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
  },
  passwordContainerFocused: {
    borderColor: '#A3A3A3',
    borderWidth: 2,
    borderRadius: 12,
  },
  passwordInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 12,
    paddingHorizontal: spacing.md,
    paddingVertical: hp(12),
    paddingRight: wp(50),
    fontSize: fs(16),
    fontFamily: FONTS.regular,
    color: '#000000',
    minHeight: hp(48),
  },
  eyeIcon: {
    position: 'absolute',
    right: spacing.md,
    padding: wp(4),
  },
  registerButton: {
    backgroundColor: '#0000FF',
    borderRadius: 12,
    paddingVertical: hp(10),
    alignItems: 'center',
    marginTop: hp(24),
    minHeight: hp(52),
    justifyContent: 'center',
  },
  registerButtonDisabled: {
    opacity: 0.6,
  },
  registerButtonText: {
    color: '#FFFFFF',
    fontSize: fs(16),
    fontFamily: FONTS.semibold,
  },
  orText: {
    textAlign: 'center',
    fontSize: fs(16),
    fontFamily: FONTS.semibold,
    color: '#000000',
    marginVertical: hp(10),
  },
  kingschatButton: {
    backgroundColor: '#1E90FF',
    borderRadius: 12,
    paddingVertical: hp(10),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: hp(40),
    minHeight: hp(52),
  },
  kingschatIcon: {
    width: wp(26),
    height: hp(26),
    marginLeft: wp(8),
  },
  kingschatButtonText: {
    color: '#FFFFFF',
    fontSize: fs(16),
    fontFamily: FONTS.semibold,
  },
  forgotPasswordContainer: {
    alignSelf: 'flex-start',
    marginTop: hp(8),
  },
  forgotPasswordText: {
    color: '#666',
    fontSize: fs(14),
    fontFamily: FONTS.regular,
  },
});
